version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "go.mongodb.org/mongo-driver"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
