version: 2
builds:
  - binary: mackerel-plugin-mongodb
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: mackerelio
    name: mackerel-plugin-mongodb

